// Generate the rave.page API client from the live dev OpenAPI spec.
//
// Zero deps beyond node + the installed `openapi-typescript-codegen@0.30.0`.
// Run: `pnpm generate-api`. Output `src/adapters/ravepage/api-client/` is
// GENERATED — never hand-edit; re-run this instead.
//
// Steps:
//   1. Resolve spec: RAVE_API_SPEC_FILE (local path) else fetch
//      RAVE_API_SPEC_URL (default https://development.api.rave.page/openapi.json).
//   2. Write it pretty-printed to src/adapters/ravepage/openapi.json (checked in
//      for reproducible regen + reviewable diffs; public API metadata only).
//   3. Clean the output dir, run codegen with the same flags rave.page uses
//      (httpClient fetch, useOptions, useUnionTypes, exportCore/Services/Models;
//      exportSchemas OFF). rave.page also passes `unwrapResponseData`+`prettier`,
//      but codegen 0.30.0 ignores both (not in its Options type); the base
//      generator already returns the response body from services, so services
//      are "unwrapped" by construction — no extra post-process needed for that.
//   4. Deterministic post-process of generated core/*.ts for the repo's strict
//      tsconfig (verbatimModuleSyntax, noUncheckedIndexedAccess). Each transform
//      is a documented string edit; hand-editing generated files is forbidden.
//   5. Write api-client/README.md.
//
// Idempotent: run twice → `git status` clean (codegen output is deterministic
// for a given spec; back-to-back runs fetch the same spec).
//
// BASE/TOKEN are intentionally NOT wired here — P3 owns auth + transport. Core
// imports only generated model TYPES.

import pkg from 'openapi-typescript-codegen';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const { generate } = pkg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const SPEC_URL = process.env.RAVE_API_SPEC_URL || 'https://development.api.rave.page/openapi.json';
const SPEC_FILE = process.env.RAVE_API_SPEC_FILE || '';
const ADAPTER_DIR = path.join(__dirname, 'src', 'adapters', 'ravepage');
const SPEC_OUT = path.join(ADAPTER_DIR, 'openapi.json');
const OUT_DIR = path.join(ADAPTER_DIR, 'api-client');

async function loadSpec() {
  if (SPEC_FILE) {
    const p = path.isAbsolute(SPEC_FILE) ? SPEC_FILE : path.join(__dirname, SPEC_FILE);
    console.log('spec: local file', p);
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  }
  console.log('spec: fetch', SPEC_URL);
  // TLS verification stays ON: a cert failure is a loud signal to fix the cert,
  // not something to silently bypass. Use RAVE_API_SPEC_FILE for offline regen.
  const res = await fetch(SPEC_URL, { headers: { Accept: 'application/json' } });
  if (!res.ok) throw new Error(`spec fetch ${res.status} ${res.statusText}`);
  return res.json();
}

// verbatimModuleSyntax guard: type-only imports must use `import type`. codegen
// 0.30.0's output already does (verified clean under the strict base tsconfig),
// so these rewrites currently match nothing — they exist to keep the client
// compiling deterministically if a future spec/codegen shift reintroduces a
// value-form import of a type-only core symbol. Never hand-edit generated files.
function fixVerbatimModuleSyntax(dir) {
  const edits = [
    // core/request.ts imports these interfaces as values.
    ['core/request.ts', /^import \{ ApiRequestOptions \}/m, 'import type { ApiRequestOptions }'],
    ['core/request.ts', /^import \{ OpenAPIConfig \}/m, 'import type { OpenAPIConfig }'],
    ['core/request.ts', /^import \{ ApiResult \}/m, 'import type { ApiResult }'],
    // CancelablePromise + ApiError are concrete classes — leave as value imports.
  ];
  for (const [rel, re, repl] of edits) {
    const f = path.join(dir, rel);
    if (!fs.existsSync(f)) continue;
    const src = fs.readFileSync(f, 'utf8');
    if (re.test(src)) fs.writeFileSync(f, src.replace(re, repl), 'utf8');
  }
}

async function main() {
  const spec = await loadSpec();
  const paths = Object.keys(spec.paths || {}).length;
  const schemas = Object.keys(spec.components?.schemas || {}).length;
  console.log(`spec ok: openapi=${spec.openapi || spec.swagger} paths=${paths} schemas=${schemas}`);
  if (!spec.paths || !schemas) throw new Error('spec missing paths/schemas');

  fs.mkdirSync(ADAPTER_DIR, { recursive: true });
  fs.writeFileSync(SPEC_OUT, JSON.stringify(spec, null, 2) + '\n', 'utf8');

  if (fs.existsSync(OUT_DIR)) fs.rmSync(OUT_DIR, { recursive: true, force: true });

  await generate({
    input: spec,
    output: OUT_DIR,
    httpClient: 'fetch',
    useOptions: true,
    useUnionTypes: true,
    exportCore: true,
    exportServices: true,
    exportModels: true,
    exportSchemas: false,
  });

  fixVerbatimModuleSyntax(OUT_DIR);

  fs.writeFileSync(
    path.join(OUT_DIR, 'README.md'),
    'Generated by `pnpm generate-api` from openapi.json — do not edit.\n',
    'utf8',
  );

  const models = fs.existsSync(path.join(OUT_DIR, 'models'))
    ? fs.readdirSync(path.join(OUT_DIR, 'models')).length
    : 0;
  const services = fs.existsSync(path.join(OUT_DIR, 'services'))
    ? fs.readdirSync(path.join(OUT_DIR, 'services')).length
    : 0;
  console.log(`generated: ${models} models, ${services} services → ${OUT_DIR}`);
}

main().catch((e) => {
  console.error('generate-api failed:', e?.stack || e);
  process.exit(1);
});
